"""Regenerate app/data/fortune500.py from a Fortune 500 CSV.

Every ticker is checked against Yahoo before it is written, so the roster never
ships a symbol that would return empty market data. Run from backend/:

    python scripts/build_fortune500.py path/to/fortune-500.csv

The CSV needs at least `Company` and `Ticker` columns; `Industry` is used as the
blurb for the mutuals and co-ops that have no ticker.
"""

from __future__ import annotations

import csv
import json
import sys
import time
from pathlib import Path
from typing import Any

import httpx

CHART = "https://query1.finance.yahoo.com/v8/finance/chart/{symbol}"
SEARCH = "https://query2.finance.yahoo.com/v1/finance/search"
UA = (
    "CompanyPulse/1.0 (https://github.com/rao-manish-24/company-insights-app; "
    "roster build script)"
)
PACE_SECONDS = 0.35
MAX_RETRIES = 4


def _get(client: httpx.Client, url: str, params: dict[str, Any]) -> Any | None:
    """Return parsed JSON, or None when Yahoo says the symbol does not exist."""
    for attempt in range(MAX_RETRIES):
        try:
            response = client.get(url, params=params)
        except Exception as exc:
            print(f"    network error: {exc}", file=sys.stderr)
            time.sleep(2 * (attempt + 1))
            continue
        if response.status_code == 429 or response.status_code >= 500:
            wait = 5 * (attempt + 1)
            print(f"    throttled ({response.status_code}), sleeping {wait}s", file=sys.stderr)
            time.sleep(wait)
            continue
        if response.status_code == 404:
            return None
        if response.status_code != 200:
            return None
        try:
            return response.json()
        except Exception:
            return None
    return None


def validate_symbol(client: httpx.Client, symbol: str) -> str | None:
    payload = _get(client, CHART.format(symbol=symbol), {"interval": "1d", "range": "5d"})
    if not isinstance(payload, dict):
        return None
    result = ((payload.get("chart") or {}).get("result") or [None])[0]
    if not isinstance(result, dict):
        return None
    meta = result.get("meta") or {}
    resolved = str(meta.get("symbol") or "").strip().upper()
    if not resolved:
        return None
    return resolved if meta.get("regularMarketPrice") is not None else None


def search_symbol(client: httpx.Client, company: str) -> str | None:
    payload = _get(
        client,
        SEARCH,
        {"q": company, "quotesCount": 6, "newsCount": 0, "enableFuzzyQuery": "false"},
    )
    if not isinstance(payload, dict):
        return None
    for quote in payload.get("quotes") or []:
        if not isinstance(quote, dict):
            continue
        if quote.get("quoteType") != "EQUITY":
            continue
        symbol = str(quote.get("symbol") or "").strip().upper()
        # Skip foreign listings of the same business (e.g. WMT.MX for Walmart).
        if symbol and "." not in symbol:
            return symbol
    return None


MODULE_HEADER = '''"""Fortune 500 roster — generated by scripts/build_fortune500.py. Do not edit.

Membership here is treated as proof a company is real, which is what keeps the
Fortune 500 working when Wikidata/Yahoo are throttled or return the founder's
person entry instead of the firm.

A ticker is present only when Yahoo confirmed that exact symbol is still live.
Renamed, merged, or delisted companies keep an empty ticker so market data is
resolved by live search rather than from a stale symbol.
"""

# (company name, ticker or "", industry)
FORTUNE500: tuple[tuple[str, str, str], ...] = (
'''


def emit_module(rows: list[dict[str, Any]]) -> None:
    lines = [MODULE_HEADER]
    for item in rows:
        # Only exact matches: a search-based "fix" can land on a different
        # business (Hess -> HESM is Hess Midstream, not Hess Corporation).
        ticker = item["ticker"] if item["state"] == "ok" else ""
        name = item["company"].replace('"', '\\"')
        industry = item["industry"].replace('"', '\\"')
        lines.append(f'    ("{name}", "{ticker}", "{industry}"),\n')
    lines.append(")\n")
    dest = Path("app/data/fortune500.py")
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text("".join(lines), encoding="utf-8")
    with_ticker = sum(1 for item in rows if item["state"] == "ok")
    print(f"Wrote {dest}: {len(rows)} companies, {with_ticker} with a verified ticker")


def main() -> int:
    if len(sys.argv) < 2:
        print(__doc__)
        return 2
    if sys.argv[1] == "--emit":
        emit_module(json.loads(Path("scripts/fortune500_validated.json").read_text("utf-8")))
        return 0
    source = Path(sys.argv[1])
    rows = [
        row
        for row in csv.DictReader(source.open(newline="", encoding="utf-8"))
        if (row.get("Company") or "").strip()
    ]
    print(f"Loaded {len(rows)} companies from {source}")

    out: list[dict[str, Any]] = []
    with httpx.Client(timeout=15.0, headers={"User-Agent": UA}, follow_redirects=True) as client:
        for index, row in enumerate(rows, start=1):
            company = " ".join(str(row["Company"]).split())
            industry = " ".join(str(row.get("Industry") or "").split())
            raw = str(row.get("Ticker") or "").strip().upper()
            final: str | None = None
            if raw:
                final = validate_symbol(client, raw)
                time.sleep(PACE_SECONDS)
                if not final:
                    # Stale symbols (BRKA) still have a live listing under a new one.
                    candidate = search_symbol(client, company)
                    time.sleep(PACE_SECONDS)
                    if candidate:
                        final = validate_symbol(client, candidate)
                        time.sleep(PACE_SECONDS)
            state = "ok" if final == raw else ("fixed" if final else "no-ticker")
            out.append(
                {
                    "company": company,
                    "industry": industry,
                    "csv_ticker": raw,
                    "ticker": final,
                    "state": state,
                }
            )
            if state != "ok":
                print(f"  [{index}/{len(rows)}] {company}: {raw or '(none)'} -> {final} ({state})")

    dest = Path("scripts/fortune500_validated.json")
    dest.write_text(json.dumps(out, indent=2, ensure_ascii=False), encoding="utf-8")
    counts: dict[str, int] = {}
    for item in out:
        counts[item["state"]] = counts.get(item["state"], 0) + 1
    print(f"Wrote {dest} ({len(out)} rows): {counts}")
    emit_module(out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
